global:
  scrape_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 172.20.0.1:9093 #Alertmanager target 

rule_files:
  - "/etc/prometheus/alert-rules/*.yaml"  # rule for Alertmanager

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.20.0.1:9100']
